#22 filtering bar
WildCodeSchool/lyon-js-react-march21-g2-p2 pull request #55
Opened 2021-04-15 10:27 UTC by edouardmisset

Creating a filter bar to filter through the displayed movies

2021-04-21 14:21 UTC, edouardmisset commented
Filters work & the style matches the rest of the app.

2021-04-21 14:29 UTC, ComicScrip requested changes

2021-04-21 14:29 UTC, ComicScrip commented on src/components/ConvertGenreIdToName.js
> +  'https://api.themoviedb.org/3/discover/movie?api_key=f22eb05a70b166bd4e2c1312e15d8e8b';
Please put the API key in a (non-versionned) `.env` and a dummy value in a (versionned)`.env.sample` file.
See https://create-react-app.dev/docs/adding-custom-environment-variables/

2021-04-21 14:29 UTC, ComicScrip commented on src/components/ConvertGenreIdToName.js
> + * @description Function to return a list of movies (or a single movie) with the genres converted to names
Oh you tried JSDoc, that's nice :)

2021-04-21 15:45 UTC, edouardmisset commented on src/components/ConvertGenreIdToName.js
> +  'https://api.themoviedb.org/3/discover/movie?api_key=f22eb05a70b166bd4e2c1312e15d8e8b';
Fixed this :)

2021-04-21 15:46 UTC, edouardmisset commented
@ComicScrip : Can you merge our PR please ?

2021-04-22 08:48 UTC, ComicScrip requested changes

2021-04-22 08:48 UTC, ComicScrip commented on .gitignore
> +.env.sample
.env should not be versionned, but .env.sample should be versionned

2021-04-22 10:15 UTC, edouardmisset commented on .gitignore
> +.env.sample
ok

2021-04-22 10:28 UTC, edouardmisset commented
Fixed ?

2021-04-22 10:31 UTC, edouardmisset commented
Oups PR should be into dev not main. Do you know how to change that @ComicScrip  ?

2021-04-23 08:10 UTC, merged